waltid:
  base_url: "http://localhost:7001"
  register_endpoint: "/wallet-api/auth/register"
  login_endpoint: "/wallet-api/auth/login"
  walletID_endpoint: "/wallet-api/wallet/accounts/wallets"
  credentials_endpoint: "/wallet-api/wallet/{wallet}/credentials"
  keys_endpoint: "/wallet-api/wallet/{wallet}/keys"
  key_export_endpoint: "/wallet-api/wallet/{wallet}/keys/{key}/export"
  default_did_endpoint: "/wallet-api/wallet/{wallet}/dids"
  match_creds_endpoint: "/wallet-api/wallet/{wallet}/exchange/matchCredentialsForPresentationDefinition"
  credential_id_endpoint: "/wallet-api/wallet/{wallet}/credentials/{credential_id}"

DIDs:
  alice: "did:jwk:eyJrdHkiOiJFQyIsImNydiI6IlAtMjU2Iiwia2lkIjoiZDQ5UFAzQ2oycnQwX0Rha2stN3VvQzFpS1I5QXNrQkpIN1lrTFFXRW9vUSIsIngiOiJFQzZIRzhOWlZLSy1EaVVQY3NkWktnUGxxbUpFMVVHZmJsbkRwSHBjcTZrIiwieSI6IjBfV1lrN2ljMk12ekd1WWJtOWJBcjM0Vkxkb2F4VndscVZUTjVIMmhlRmMifQ"
  bob: "did:jwk:eyJrdHkiOiJFQyIsImNydiI6IlAtMjU2Iiwia2lkIjoieUpUdlJMelZtZC1Rc3NFWjllT1d4Qm8xOTNiUDE2NG50UzVjdUQxaVVZbyIsIngiOiJvOTVXME8xYjlhclJkZGRpeGdEaDdGWVRpVUNUeUhodlN4RlhIVU00aDBZIiwieSI6Ilk5eHdHZFBGWUN5Q29oT3ZadDJaSXpjMHpVZnhwallZNkR0RENRd205Tm8ifQ"

A2A:
  bob_base_url: "https://localhost:8443"
  a2a_did_auth_uri: "https://example.com/extensions/a2a-didauth/v1"

MSEntraID:
  az_tenant_id: "070bd82a-c7ba-4bed-bc50-3dca476dc820"
  az_client_id: "50ceec05-8538-4fb2-8910-3f8ad40aba4c"
  az_oauth_scope: "3db474b9-6a0c-4840-96ac-1fceb342124f/.default"
  issuer_api_url: "https://verifiedid.did.msidentity.com/v1.0/verifiableCredentials/createIssuanceRequest"
  verifier_api_url: "https://verifiedid.did.msidentity.com/v1.0/verifiableCredentials/createPresentationRequest"
  did_authority: "did:web:stgacctestdid.z38.web.core.windows.net"
  manifest: "https://verifiedid.did.msidentity.com/v1.0/tenants/070bd82a-c7ba-4bed-bc50-3dca476dc820/verifiableCredentials/contracts/ac297af7-9061-096d-25be-f4b73ee7e37d/manifest"
  callback_url: "https://callback-webhook.azurewebsites.net/"

colors:
  RED: "\u001b[31m"
  GREEN: "\u001b[32m"
  YELLOW: "\u001b[33m"
  BLUE: "\u001b[34m"
  MAGENTA: "\u001b[35m"
  CYAN: "\u001b[36m"
  RESET: "\u001b[0m"